import { useState, useEffect, useMemo, useCallback, useRef } from 'react'
import { useTranslation } from 'react-i18next'
import { useTheme } from '@/hooks/useTheme'
import { PanelSkeleton } from '@/components/ui/skeleton'
import type { PanelProps } from './PanelRegistry'
import type { CodePanelData } from '@/types/panel-data'

/** Map resolved app theme to a shiki highlighting theme */
function getShikiTheme(resolved: string): string {
  switch (resolved) {
    case 'light':
    case 'vintage':
      return 'github-light'
    case 'dark':
    case 'doodle':
      return 'github-dark'
    default:
      return 'github-dark'
  }
}

function isCodePanelData(data: unknown): data is CodePanelData {
  if (data == null || typeof data !== 'object') return false
  const obj = data as Record<string, unknown>
  return typeof obj['language'] === 'string' && typeof obj['code'] === 'string'
}

/**
 * Split shiki HTML output into individual lines and optionally highlight specific lines.
 * Shiki outputs a <pre><code>...lines...</code></pre> structure.
 * We inject highlight wrappers around lines that match highlightLines.
 */
function applyLineHighlights(html: string, highlightLines: number[]): string {
  if (highlightLines.length === 0) return html

  const highlightSet = new Set(highlightLines)

  // Shiki wraps lines in <span class="line">...</span>
  // We replace the line spans that match with a highlighted version
  let lineIndex = 0
  return html.replace(/<span class="line">/g, (match) => {
    lineIndex++
    if (highlightSet.has(lineIndex)) {
      return '<span class="line code-line-highlight">'
    }
    return match
  })
}

function CopyButton({ code }: { code: string }) {
  const { t } = useTranslation('panels')
  const [copied, setCopied] = useState(false)
  const timerRef = useRef<ReturnType<typeof setTimeout>>(null)

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true)
      if (timerRef.current) clearTimeout(timerRef.current)
      timerRef.current = setTimeout(() => setCopied(false), 2000)
    })
  }, [code])

  useEffect(() => {
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current)
    }
  }, [])

  return (
    <button
      onClick={handleCopy}
      className="absolute top-2 right-2 z-10 px-2 py-1 rounded text-xs backdrop-blur-sm bg-background/80 hover:bg-muted/50 text-muted-foreground hover:text-foreground opacity-0 group-hover:opacity-100 transition-opacity focus-visible:opacity-100 focus-visible:ring-2 focus-visible:ring-ring/50 focus-visible:outline-none"
      aria-label={t('copy_code')}
    >
      {copied ? (
        <span className="text-panel-copy-success">{t('copied')}</span>
      ) : (
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
        </svg>
      )}
    </button>
  )
}

function LineNumbers({ count }: { count: number }) {
  return (
    <div
      className="shrink-0 text-right pr-2 pt-3 pb-3 select-none text-muted-foreground/60 text-[11px] font-mono tabular-nums leading-[1.6] border-r border-border/15"
      style={{ userSelect: 'none' }}
      aria-hidden="true"
    >
      {Array.from({ length: count }, (_, i) => (
        <div key={i + 1} className="px-1.5">
          {i + 1}
        </div>
      ))}
    </div>
  )
}

function FallbackCodeView({ code, lineCount }: { code: string; lineCount: number }) {
  return (
    <div className="flex min-h-0 flex-1 overflow-auto">
      <LineNumbers count={lineCount} />
      <div className="flex-1 overflow-x-auto relative">
        <div className="absolute inset-0 p-4">
          <PanelSkeleton type="code" />
        </div>
        <pre className="px-3 py-3 text-xs font-mono leading-[1.6] opacity-50">
          <code className="text-muted-foreground">{code}</code>
        </pre>
      </div>
    </div>
  )
}

function HighlightedCodeView({
  html,
  lineCount,
}: {
  html: string
  lineCount: number
}) {
  return (
    <div className="flex min-h-0 flex-1 overflow-auto">
      <LineNumbers count={lineCount} />
      <div
        className="flex-1 overflow-x-auto [&_pre]:px-3 [&_pre]:py-3 [&_pre]:m-0 [&_pre]:bg-transparent [&_pre]:text-xs [&_pre]:leading-[1.6] [&_code]:text-xs [&_code]:leading-[1.6]"
        // SECURITY: HTML is generated by Shiki syntax highlighter (trusted)
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  )
}

export function CodePanel({ data, panelId }: PanelProps) {
  const { t } = useTranslation('panels')
  const { resolved: currentTheme } = useTheme()
  const [highlightedHtml, setHighlightedHtml] = useState<string | null>(null)
  const [error, setError] = useState(false)

  const codeData = useMemo(() => {
    if (isCodePanelData(data)) return data
    return null
  }, [data])

  const code = codeData?.code ?? ''
  const language = codeData?.language ?? 'text'
  const highlightLines = codeData?.highlightLines ?? []
  const copyable = codeData?.copyable !== false
  const filename = codeData?.filename

  const lineCount = useMemo(() => {
    if (!code) return 0
    return code.split('\n').length
  }, [code])

  // Load shiki and highlight code — re-runs when theme changes
  const shikiTheme = getShikiTheme(currentTheme)

  useEffect(() => {
    if (!code) {
      setHighlightedHtml(null)
      return
    }

    let cancelled = false
    setHighlightedHtml(null)
    setError(false)

    async function highlight() {
      try {
        const { codeToHtml } = await import('shiki/bundle/web')
        if (cancelled) return

        const html = await codeToHtml(code, {
          lang: language,
          theme: shikiTheme,
        })
        if (cancelled) return

        const processed = applyLineHighlights(html, highlightLines)
        setHighlightedHtml(processed)
      } catch {
        if (!cancelled) {
          setError(true)
        }
      }
    }

    highlight()
    return () => {
      cancelled = true
    }
  }, [code, language, highlightLines, shikiTheme])

  if (!codeData) {
    return (
      <div className="flex items-center justify-center h-full p-4 text-sm text-muted-foreground">
        {t('cannot_render', { type: t('code') })}: {t('invalid_data')} (panelId: {panelId})
      </div>
    )
  }

  if (!code) {
    return (
      <div className="flex items-center justify-center h-full p-4 text-sm text-muted-foreground">
        {t('no_code')}
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full bg-muted/30 overflow-hidden">
      {/* Filename label */}
      {filename && (
        <div className="text-[11px] text-muted-foreground bg-muted/60 px-2.5 py-0.5 border-b border-border/30 font-mono">
          {filename}
        </div>
      )}

      {/* Code area */}
      <div className="group relative flex-1 min-h-0 flex flex-col">
        {copyable && <CopyButton code={code} />}

        {highlightedHtml ? (
          <HighlightedCodeView html={highlightedHtml} lineCount={lineCount} />
        ) : error ? (
          /* Fallback without animation if shiki failed */
          <div className="flex min-h-0 flex-1 overflow-auto">
            <LineNumbers count={lineCount} />
            <div className="flex-1 overflow-x-auto">
              <pre className="px-3 py-3 text-xs font-mono leading-[1.6]">
                <code className="text-muted-foreground">{code}</code>
              </pre>
            </div>
          </div>
        ) : (
          <FallbackCodeView code={code} lineCount={lineCount} />
        )}
      </div>
    </div>
  )
}
